export enum UserSeniority{
    JUNIOR_CONSULTANT="JUNIOR_CONSULTANT",
    CONSULTANT="CONSULTANT",
    SENIOR_CONSULTANT="SENIOR_CONSULTANT",
    MANAGER="MANAGER",
    SENIOR_MANAGER="SENIOR_MANAGER",
    ASSOCIATED_PARTNER="ASSOCIATED_PARTNER",
    PARTNER="PARTNER"
}
